### ISSUE TITLE
基于MtContextThreadLocal的ThreadContextMap实现

### ISSUE THREAD

**Issue by bwzhang2011** [oldratlee/log4j-slf4j-impl-patch-mtc#1]
@oldratlee，log4j2中的ThreadContext提供了ThreadContextMap的机制。可以自定义实现ThreadContextMap，由于ThreadContextMap没有彻底解决上下文变量在跨线程中传递失效的问题，而MTC可以比较好的解决。MTC应该提供一个基于MtContextThreadLocal的ThreadContextMap的实现。而由应用来决定启用自定义的ThreadContextMap的实现（做到插件和非侵入）

**Comment by bwzhang2011** [comment]
@oldratlee， 我将原ThreadContextMap的实现中inheriLocal的部分替换成mtc方式，也能够调通。但有一个细微的差别就是mtc的构造的地方 initialValue() 以及 T childValue(T parentValue) 这两个方法的覆写。缺省实现中initialValue返回的为null，而initialValue（）在patch里面的是new HashMap<String,String>()

**Comment by bwzhang2011** [comment]
@oldratlee, 有时间可否协助看一下。

**Comment by oldratlee** [comment]
> 有一个细微的差别就是`MTC`的构造的地方`initialValue()`以及`T childValue(T parentValue)`这两个方法的覆写。缺省实现中`initialValue`返回的为`null`，而`initialValue`在`patch`里面的是`new HashMap<String,String>()`

这个没关系的。

如果`initialValue`返回的为`null`，即是首次`java.lang.ThreadLocal#get`方法返回的内容。不使用`initialValue`，可以后面自己`java.lang.ThreadLocal#set`。

`patch`实现返回`HashMap`，只是在`java.lang.ThreadLocal#get`后的处理方便些。

**Comment by bwzhang2011** [comment]
@oldratlee, 感谢回复。如你所指出的，当前针对ThreadContextMap的实现——即inheriLocal的部分替换成MTC方式（其余的绝大部分都没有变动）——应该没什么问题吧。

**Comment by oldratlee** [comment]
是的。

你可以直接把`MtContextThreadLocal` 当 `ThreadLocal` 或是 `InheritableThreadLocal`， 虽然 没有必要 :)

**Comment by bwzhang2011** [comment]
@oldratlee, 我考虑使用MTC的主要原因是LOG4J2中的MDC说明表明，当前MDC的实现即threadContext的处理不严格保证线程变量跨线程的传递，而你也知道两方面兼容就只能朝这个方向努力。考虑到threadContext的实现提供了针对threadContextMap的拔插支持，那我就没有必要使用patch的实现。转而使用MTC有关的threadContextMap的支持，这样线程传递的场景均通过MTC方式。包括threadContextMap也是如此，但如果你说没必要我就有一点疑惑了，难道这样考虑的思路存在问题麽。我有些愚钝和糊涂了。

**Comment by oldratlee** [comment]
> 包括threadContextMap也是如此，但如果你说没必要我就有一点疑惑了，难道这样考虑的思路存在问题麽。

> 你可以直接把MtContextThreadLocal 当 ThreadLocal 或是 InheritableThreadLocal， 虽然 没有必要 

上面我说的必要，是指 把`MtContextThreadLocal` 仅当作 ThreadLocal 或是 InheritableThreadLocal 来用。

> 考虑到threadContext的实现提供了针对threadContextMap的拔插支持，那我就没有必要使用patch的实现。转而使用MTC有关的threadContextMap的支持，这样线程传递的场景均通过MTC方式。

能说说 『考虑到threadContext的实现提供了针对threadContextMap的拔插支持』 ，这个做法你是怎么做的吗？ 方便 给段示意代码？

**Comment by bwzhang2011** [comment]
@oldratlee, 抱歉比较晚回复。在https://github.com/alibaba/multi-thread-context/issues/51 有回复了。
请注意看一下其中一段：
final String threadContextMapName = managerProps.getStringProperty(THREAD_CONTEXT_KEY);
final ClassLoader cl = ProviderUtil.findClassLoader();
if (threadContextMapName != null) {
try {
final Class<?> clazz = cl.loadClass(threadContextMapName);
if (ThreadContextMap.class.isAssignableFrom(clazz)) {
contextMap = (ThreadContextMap) clazz.newInstance();
}
} catch (final ClassNotFoundException cnfe) {
LOGGER.error("Unable to locate configured ThreadContextMap {}", threadContextMapName);
} catch (final Exception ex) {
LOGGER.error("Unable to create configured ThreadContextMap {}", threadContextMapName, ex);
}
}

将THREAD_CONTEXT_KEY的路径指向你自己实现的threadContextMap即可，这样就做到了拔插。
鼎哥，你就在patch中增加一个基于mtcthreadLocal的threadContextMap就好了。

**Comment by oldratlee** [comment]
收到。

我瞧瞧 :smile:

**Comment by bwzhang2011** [comment]
@oldratlee, 进展得怎么样了。现在在MDC中提取数据（格式通过RFC5424)遇到了跟[KEY1=VALUE KEY2=VALUE KEY3=VALUE3] 的提取数据问题， 就是总括号里面的数据需要提取进行编排。但如果简单实用空格分隔符会遇到 VALUE中如果存在空格 则会截断的问题。鼎哥可否提供针对KEY=VALUE的字符串的正则表达式

**Comment by oldratlee** [comment]
> 将THREAD_CONTEXT_KEY的路径指向你自己实现的threadContextMap即可，这样就做到了拔插。

按你的这个方案，实现了 https://github.com/oldratlee/log4j2-mtc-thread-context-map

把这个依赖放到项目中，即开启 `MtcThreadContextMap`

**Comment by bwzhang2011** [comment]
@oldratlee, 感谢回复，看外代码差别是在初始化的部分（我会将其MERGE到现在的工程或者使用你这个）。的确诚如你指出的，我们需要用DEMO的方式这样便于大家沟通。至于RFC5424的部分，就LOG4J2或其他而言，是LAYOUT的一种格式。数据上送（配置成那样），就产生了[]那样的格式数据。这部分数据就是MDC里面的数据——后面还有啥子问题再多沟通交流。

**Comment by oldratlee** [comment]
经你提醒，初始化部分我的代码是多余的。 我CV代码了，测试通过后没有多想。

已经修改了，顺便发了Maven中央库，方便使用：

```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>log4j2-mtc-thread-context-map</artifactId>
    <version>1.0.1</version>
</dependency>
```

PS：

> 外代码差别是在初始化的部分（我会将其MERGE到现在的工程或者使用你这个）。

@bwzhang2011 方便给一下你的代码？这样看一下方便发现我的问题 :smile:

**Comment by oldratlee** [comment]
> @bwzhang2011 方便给一下你的代码？这样看一下方便发现`log4j2-mtc-thread-context-map`问题。
> 另外，[`log4j2-mtc-thread-context-map`](https://github.com/oldratlee/log4j2-mtc-thread-context-map)仓库加你了，你可以直接修改 :smile: 

你有需求要发布版本，发布到Maven中央库操作几分钟。可以直接邮件我让我来发布，我会最快发布好，保证你的使用 :smile:
