### ISSUE TITLE
是不是可以不用采用覆盖替换类的方式呢

### ISSUE THREAD

**Issue by wuwen5** [oldratlee/log4j-slf4j-impl-patch-mtc#2]
比如在org.slf4j包下增加一个类

```java
MDC.mdcAdapter = new MtcLog4jMDCAdapter();
```
这样应该会简单一点,不知道是否可以

**Comment by bwzhang2011** [comment]
如果改SLF4J的源码（即日志框架具体实现）是可以的（也是最直接的），但如果你可以局限在某个组合——比如slf4j+log4j2 那么后者提供了这个入口只需要提供里面的实现即可 比如threadContextMap，可以将其包装进来。如果鼎哥愿意给个官方实现那就最好了

**Comment by oldratlee** [comment]
> 比如在org.slf4j包下增加一个类`MDC.mdcAdapter = new MtcLog4jMDCAdapter();`  
> 这样应该会简单一点,不知道是否可以

@wuwen5 

`MDC.mdcAdapter = new MtcLog4jMDCAdapter();` 这样做的话，应该是会：  

1. 这行赋值需要应用来主动触发，对用户使用不透明。
2. 如果这行设置代码要足够靠前。如在Web应用中，要在最优先的`Filter`中完成，这样Web框架的日志操作（在应用代码之前）才是生效的。
